# The env variable `TAPEAGENTS_LLM_TOKEN` should be set to your openrouter token.
_target_: tapeagents.llms.TrainableLLM
model_name: meta-llama/Llama-3.1-405B-Instruct
stream: false
use_cache: false
context_size: 128000
base_url: https://openrouter.ai/api
parameters:
  temperature: 1.0
