exp_name: test_remote_async_webagent
exp_path: outputs/rl_webagent/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

train_split: 0.6  # 0.6 of tasks for training, 0.4 for testing
seeds: [0, 42, 1337, 900, 103]

environment_variables:
  miniwob_url: file:///home/toolkit/miniwob-plusplus/miniwob/html/miniwob/
  # for workarena, create instance here https://github.com/ServiceNow/WorkArena?tab=readme-ov-file#a-create-a-servicenow-developer-instance
  # snow_instance_url: ???
  # snow_instance_uname: ???
  # snow_instance_pwd: ???

llm:
  _target_: tapeagents.llms.TrainableLLM
  base_url: ???
  model_name: ???
  use_litellm_tokenizer_fallback: true
  use_cache: false
  context_size: 32000
  parameters:
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.8 # from https://huggingface.co/Qwen/Qwen3-8B for non-thinking mode. For thinking mode use t=0.6 p=0.95
    top_k: 20
    chat_template_kwargs:
      enable_thinking: false

environment:
  _target_: tapeagents.remote_environment.AsyncRemoteEnvironment
  server_url: http://localhost:8000

agent:
  _target_: tapeagents.agent.Agent
  name : web_agent
  max_iterations: 2
  llms:
    default: ${llm}
  templates: ??? # TODO
  nodes: ??? # TODO

hydra:
  run:
    dir: ${exp_path}