exp_name: test_remote_async_webagent
exp_path: outputs/rl_webagent/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

train_split: 0.6  # 0.6 of tasks for training, 0.4 for testing
seeds: [0, 42, 1337, 900, 103]

environment_variables:
  miniwob_url: file:///home/toolkit/miniwob-plusplus/miniwob/html/miniwob/
  # for workarena, create instance here https://github.com/ServiceNow/WorkArena?tab=readme-ov-file#a-create-a-servicenow-developer-instance
  # snow_instance_url: ???
  # snow_instance_uname: ???
  # snow_instance_pwd: ???

llm:
  _target_: tapeagents.llms.TrainableLLM
  base_url: ???
  model_name: ???
  use_litellm_tokenizer_fallback: true
  use_cache: false
  context_size: 32000
  parameters:
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.8 # from https://huggingface.co/Qwen/Qwen3-8B for non-thinking mode. For thinking mode use t=0.6 p=0.95
    top_k: 20
    chat_template_kwargs:
      enable_thinking: false

environment:
  _target_: tapeagents.remote_environment.AsyncRemoteEnvironment
  server_url: http://localhost:8000

agent:
  _target_: tapeagents.agent.Agent
  name : web_agent
  max_iterations: 4
  store_llm_calls: true
  llms:
    default: ${llm}
  templates:
    system_prompt: |
      You are an expert AI Agent, your goal is to help the user perform tasks using a web browser.
      Your role is to understand user queries and respond in a helpful and accurate manner.
      Keep your replies concise and direct. Prioritize clarity and avoid over-elaboration.
      You will be provided with the content of the current page and a task from the user.
      Do not express your emotions or opinions about the user question.
    allowed_steps: |
      You are allowed to produce ONLY steps with the following json schemas:
      {allowed_steps}
      Do not reproduce schema when producing the steps, use it as a reference.
  nodes:
    - _target_: examples.rl_webagent.agent.WebNode
      name: set_goal
      guidance: |
        Produce the reasoning_thought step that describes the intended solution to the task. In the reasoning lines:
        - review the instructions from the user and the content of the page.
        - outline the main task to be accomplished and the steps to be taken to achieve it.
        - produce definiton of done, that will be checked later to verify if the task was completed.
        Produce only one step!
      system_prompt: ${agent.templates.system_prompt}
      steps_prompt: ${agent.templates.allowed_steps}
      steps: examples.rl_webagent.steps.ReasoningThought
      trim_obs_except_last_n: 3  # keep the last 3 observations from the tape in prompt messages
      max_chars_page_observation: 3000  # keep up to 3000 chars in PageObservation steps
    - _target_: examples.rl_webagent.agent.WebNode
      name: reflect
      guidance: |
        Review the current state of the page and previous steps to find the best possible next action to accomplish the task.
        Produce the reflection_thought to describe the current page state, reflect on your last action, describe what is left to do, and what will be the immediate next action.
        Produce only one reflection_thought step!
      system_prompt: ${agent.templates.system_prompt}
      steps_prompt: ${agent.templates.allowed_steps}
      steps: examples.rl_webagent.steps.WebAgentStep
      trim_obs_except_last_n: 3  # keep the last 3 observations from the tape in prompt messages
      max_chars_page_observation: 3000  # keep up to 3000 chars in PageObservation steps
    - _target_: examples.rl_webagent.agent.WebNode
      name: act
      guidance: |
        Produce the next action to be performed with the current page.
        If you think that the task is solved, produce the final_answer_action.
        You can interact with the page elements using their BIDs or coordinates as arguments for actions.
        HINTS:
        - You can use the BIDs of the elements or the mouse position in x, y coordinates to interact with them.
        - To select value in a dropdown or combobox, ALWAYS use select_action.
        - To click on a checkbox or radio button, ALWAYS use BID (or coordinates) of the corresponding Text and not the BID (or coordinates) of the element itself.
        - Press enter key to submit the search query.
        - Always produce only one step at a time.
        - Step kind is always lowercase and underscore separated.
      system_prompt: ${agent.templates.system_prompt}
      steps_prompt: ${agent.templates.allowed_steps}
      steps: examples.rl_webagent.steps.WebAgentAction
      trim_obs_except_last_n: 3  # keep the last 3 observations from the tape in prompt messages
      max_chars_page_observation: 3000  # keep up to 3000 chars in PageObservation steps
      next_node: reflect

hydra:
  run:
    dir: ${exp_path}