defaults:
  - _self_
  - llm: gpt4o

environment:
  _target_: tapeagents.environment.ToolCollectionEnvironment
  tools:
    - _target_: tapeagents.tools.calculator.Calculator
    - _target_: tapeagents.tools.memory.MemoryTool

agent:
  _target_: tapeagents.agent.Agent
  name: calculator_agent
  max_iterations: 2
  llms:
    default: ${llm}
  templates:
    system_prompt: |
      You will help the user perform calculations.
      When you perform a calculation, store the results in memory.
      Before performing any calculation, check if the result is already in memory.
      If you encounter the same calculation request, you can use the result from memory instead of performing the calculation.
    allowed_tools: |
      You have access to the following tools:
      {tools_description}
    thought_format: |
      Important! Respond with the plain text, do not include any JSON or code.
      Do not output anything besides what I asked in this message.
    allowed_steps: |
      You have access to the following tools:
      {tools_description}
      You are allowed to produce ONLY steps with the following JSON schemas:
      {allowed_steps}
      Do not reproduce the schema when producing steps; use it as a reference.
    format: >
      Output only a single JSON dict. 
      DO NOT OUTPUT ANYTHING BESIDES THE JSON! DO NOT PLACE ANY COMMENTS INSIDE THE JSON. 
      It will break the system that processes the output.
  nodes:
    - _target_: tapeagents.nodes.StandardNode
      name: act
      system_prompt: ${agent.templates.system_prompt}
      guidance: |
        You have access to tools to perform calculations. You have access to memory where you can store calculations and retrieve calculation results.
        ${agent.templates.format}
      steps_prompt: ${agent.templates.allowed_steps}
      steps:
        - tapeagents.dialog_tape.AssistantAnswer
      use_known_actions: true
      next_node: act
