# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.21"
          enable-cache: true
          # invalidate cache when the lockfile changes
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies and package 
        # stop the build if there are Python syntax errors or undefined names
        run: make
      - name: Linter check
        # stop the build if there are Python syntax errors or undefined names
        run: make lint-check 
      - name: Run fast tests with pytest
        run: HF_TOKEN="${{ secrets.HF_HUB_TOKEN }}" make test
      - name: Run core tests with minimal dependencies
        run: make test-core
